# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  app:
    image: andyhky:flaskuwsgi
    restart: always
    ports:
      - 9001:9001
    links:
      - db:db
